services:
  uptime-kuma:
    image: louislam/uptime-kuma
    pull_policy: always
    container_name: uptime-kuma
    volumes:
      - "${UPTIME_KUMA_CONFIG}:/app/data"
    ports:
      - "${KUMA_PORT}:3001"  # <Host Port>:<Container Port>
    restart: always
